include ../../Makefile.config

PROJ_ROOT	:= $(CURDIR)/../..
obj_dir		:= $(ROOT_OBJ_DIR)/libwic
lib_dir		:= $(ROOT_LIB_DIR)
static_lib	:= libwic.a
dynamic_lib	:= libwic.so
CPP_INCLPATHS	= $(PROJ_ROOT)

include ../../Makefile.include
