include ../../Makefile.config

PROJ_ROOT	:= $(CURDIR)/../..
obj_dir		:= $(ROOT_OBJ_DIR)/qatest
bin_dir		:= $(ROOT_BIN_DIR)
binary		:= qatest
CPP_INCLPATHS	= $(PROJ_ROOT)

include ../../Makefile.include
