include ../../Makefile.config

PROJ_ROOT	:= $(CURDIR)/../..
obj_dir		:= $(ROOT_OBJ_DIR)/wictool
bin_dir		:= $(ROOT_BIN_DIR)
binary		:= wictool
CPP_INCLPATHS	= $(PROJ_ROOT)

include ../../Makefile.include
