###

CPP		= g++
CC		= gcc
CFLAGS		= -Wall
CPPFLAGS	= -Wall
AR		= ar rcs
LD		= $(CPP)
MAKE		= make
MKDIR		= mkdir -p
RM		= rm -f

###

PROJ_ROOT	:= $(PWD)
# ifeq ($(PWD), $(CURDIR))
# 	PROJ_ROOT := $(PWD)/..
# endif
ROOT_BIN_DIR	= $(PROJ_ROOT)/bin
ROOT_OBJ_DIR	= $(PROJ_ROOT)/obj
ROOT_LIB_DIR	= $(PROJ_ROOT)/lib
ROOT_INCL_DIR	= $(PROJ_ROOT)/wic

###

LIBPATHS	= $(lib_dir)
C_INCLPATHS	= .
CPP_INCLPATHS	= .

